export const states = [
    { title: "Andhra Pradesh", value: "1" },
    { title: "Arunachal Pradesh", value: "2" },
    { title: "Assam", value: "3" },
    { title: "Bihar", value: "4" },
    { title: "Delhi", value: "5" },
    { title: "Chhattisgarh", value: "6" },
    { title: "Goa", value: "7" },
    { title: "Gujarat", value: "8" },
    { title: "Haryana", value: "9" },
    { title: "Himachal Pradesh", value: "10" },
    { title: "Jharkhand", value: "11" },
    { title: "Karnataka", value: "12" },
    { title: "Kerala", value: "13" },
    { title: "Madhya Pradesh", value: "14" },
    { title: "Maharashtra", value: "15" },
    { title: "Manipur", value: "16r" },
    { title: "Meghalaya", value: "17" },
    { title: "Mizoram", value: "18" },
    { title: "Nagaland", value: "19" },
    { title: "Odisha", value: "20" },
    { title: "Punjab", value: "21" },
    { title: "Rajasthan", value: "22" },
    { title: "Sikkim", value: "23" },
    { title: "Tamil Nadu", value: "24" },
    { title: "Telangana", value: "25" },
    { title: "Tripura", value: "26" },
    { title: "Uttar Pradesh", value: "27" },
    { title: "Uttrakhand", value: "28" },
    { title: "West Bengal", value: "29" }
];
